//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.27 at 07:08:04 AM EDT 
//


package lordgasmic.podcastremix.jaxb.podcast;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

 
/**
 * <p>Java class for channelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="channelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="docs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="managingEditor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="webMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastBuildDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ttl" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="image" type="{}imageType"/>
 *         &lt;element name="atomLink" type="{}atomLinkType"/>
 *         &lt;element name="itunesAuthor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesSubtitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesSummary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesKeywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesExplicit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesImage" type="{}itunesImageType"/>
 *         &lt;element name="itunesOwner" type="{}itunesOwnerType"/>
 *         &lt;element name="itunesBlock" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesCategory" type="{}itunesCategoryType"/>
 *         &lt;element name="item" type="{}itemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "channelType", propOrder = {
    "title",
    "link",
    "description",
    "generator",
    "docs",
    "language",
    "copyright",
    "managingEditor",
    "webMaster",
    "pubDate",
    "lastBuildDate",
    "category",
    "ttl",
    "image",
    "atomLink",
    "itunesAuthor",
    "itunesSubtitle",
    "itunesSummary",
    "itunesKeywords",
    "itunesExplicit",
    "itunesImage",
    "itunesOwner",
    "itunesBlock",
    "itunesCategory",
    "item"
})
public class ChannelType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String link;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String generator;
    @XmlElement(required = true)
    protected String docs;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String copyright;
    @XmlElement(required = true)
    protected String managingEditor;
    @XmlElement(required = true)
    protected String webMaster;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pubDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastBuildDate;
    @XmlElement(required = true)
    protected String category;
    protected int ttl;
    @XmlElement(required = true)
    protected ImageType image;
    @XmlElement(required = true)
    protected AtomLinkType atomLink;
    @XmlElement(required = true)
    protected String itunesAuthor;
    @XmlElement(required = true)
    protected String itunesSubtitle;
    @XmlElement(required = true)
    protected String itunesSummary;
    @XmlElement(required = true)
    protected String itunesKeywords;
    @XmlElement(required = true)
    protected String itunesExplicit;
    @XmlElement(required = true)
    protected ItunesImageType itunesImage;
    @XmlElement(required = true)
    protected ItunesOwnerType itunesOwner;
    @XmlElement(required = true)
    protected String itunesBlock;
    @XmlElement(required = true)
    protected ItunesCategoryType itunesCategory;
    @XmlElement(required = true)
    protected List<ItemType> item;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the generator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerator() {
        return generator;
    }

    /**
     * Sets the value of the generator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerator(String value) {
        this.generator = value;
    }

    /**
     * Gets the value of the docs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocs() {
        return docs;
    }

    /**
     * Sets the value of the docs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocs(String value) {
        this.docs = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the managingEditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagingEditor() {
        return managingEditor;
    }

    /**
     * Sets the value of the managingEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagingEditor(String value) {
        this.managingEditor = value;
    }

    /**
     * Gets the value of the webMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebMaster() {
        return webMaster;
    }

    /**
     * Sets the value of the webMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebMaster(String value) {
        this.webMaster = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPubDate() {
        return pubDate;
    }

    /**
     * Sets the value of the pubDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPubDate(XMLGregorianCalendar value) {
        this.pubDate = value;
    }

    /**
     * Gets the value of the lastBuildDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastBuildDate() {
        return lastBuildDate;
    }

    /**
     * Sets the value of the lastBuildDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastBuildDate(XMLGregorianCalendar value) {
        this.lastBuildDate = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the ttl property.
     * 
     */
    public int getTtl() {
        return ttl;
    }

    /**
     * Sets the value of the ttl property.
     * 
     */
    public void setTtl(int value) {
        this.ttl = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType }
     *     
     */
    public ImageType getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType }
     *     
     */
    public void setImage(ImageType value) {
        this.image = value;
    }

    /**
     * Gets the value of the atomLink property.
     * 
     * @return
     *     possible object is
     *     {@link AtomLinkType }
     *     
     */
    public AtomLinkType getAtomLink() {
        return atomLink;
    }

    /**
     * Sets the value of the atomLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomLinkType }
     *     
     */
    public void setAtomLink(AtomLinkType value) {
        this.atomLink = value;
    }

    /**
     * Gets the value of the itunesAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesAuthor() {
        return itunesAuthor;
    }

    /**
     * Sets the value of the itunesAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesAuthor(String value) {
        this.itunesAuthor = value;
    }

    /**
     * Gets the value of the itunesSubtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesSubtitle() {
        return itunesSubtitle;
    }

    /**
     * Sets the value of the itunesSubtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesSubtitle(String value) {
        this.itunesSubtitle = value;
    }

    /**
     * Gets the value of the itunesSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesSummary() {
        return itunesSummary;
    }

    /**
     * Sets the value of the itunesSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesSummary(String value) {
        this.itunesSummary = value;
    }

    /**
     * Gets the value of the itunesKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesKeywords() {
        return itunesKeywords;
    }

    /**
     * Sets the value of the itunesKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesKeywords(String value) {
        this.itunesKeywords = value;
    }

    /**
     * Gets the value of the itunesExplicit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesExplicit() {
        return itunesExplicit;
    }

    /**
     * Sets the value of the itunesExplicit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesExplicit(String value) {
        this.itunesExplicit = value;
    }

    /**
     * Gets the value of the itunesImage property.
     * 
     * @return
     *     possible object is
     *     {@link ItunesImageType }
     *     
     */
    public ItunesImageType getItunesImage() {
        return itunesImage;
    }

    /**
     * Sets the value of the itunesImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItunesImageType }
     *     
     */
    public void setItunesImage(ItunesImageType value) {
        this.itunesImage = value;
    }

    /**
     * Gets the value of the itunesOwner property.
     * 
     * @return
     *     possible object is
     *     {@link ItunesOwnerType }
     *     
     */
    public ItunesOwnerType getItunesOwner() {
        return itunesOwner;
    }

    /**
     * Sets the value of the itunesOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItunesOwnerType }
     *     
     */
    public void setItunesOwner(ItunesOwnerType value) {
        this.itunesOwner = value;
    }

    /**
     * Gets the value of the itunesBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesBlock() {
        return itunesBlock;
    }

    /**
     * Sets the value of the itunesBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesBlock(String value) {
        this.itunesBlock = value;
    }

    /**
     * Gets the value of the itunesCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ItunesCategoryType }
     *     
     */
    public ItunesCategoryType getItunesCategory() {
        return itunesCategory;
    }

    /**
     * Sets the value of the itunesCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItunesCategoryType }
     *     
     */
    public void setItunesCategory(ItunesCategoryType value) {
        this.itunesCategory = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getItem() {
        if (item == null) {
            item = new ArrayList<ItemType>();
        }
        return this.item;
    }

}
