//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.27 at 07:08:04 AM EDT 
//


package lordgasmic.podcastremix.jaxb.podcast;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> 
 * &lt;complexType name="itemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guid" type="{}guidType"/>
 *         &lt;element name="itunesAuthor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesSubtitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesSummary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesExplicit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itunesDuration" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enclosure" type="{}enclosureType"/>
 *         &lt;element name="media" type="{}mediaType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {
    "title",
    "description",
    "author",
    "pubDate",
    "category",
    "comments",
    "guid",
    "itunesAuthor",
    "itunesSubtitle",
    "itunesSummary",
    "itunesExplicit",
    "itunesDuration",
    "link",
    "enclosure",
    "media"
})
public class ItemType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pubDate;
    @XmlElement(required = true)
    protected List<String> category;
    @XmlElement(required = true)
    protected String comments;
    @XmlElement(required = true)
    protected GuidType guid;
    @XmlElement(required = true)
    protected String itunesAuthor;
    @XmlElement(required = true)
    protected String itunesSubtitle;
    @XmlElement(required = true)
    protected String itunesSummary;
    @XmlElement(required = true)
    protected String itunesExplicit;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itunesDuration;
    @XmlElement(required = true)
    protected String link;
    @XmlElement(required = true)
    protected EnclosureType enclosure;
    @XmlElement(required = true)
    protected MediaType media;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPubDate() {
        return pubDate;
    }

    /**
     * Sets the value of the pubDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPubDate(XMLGregorianCalendar value) {
        this.pubDate = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCategory() {
        if (category == null) {
            category = new ArrayList<String>();
        }
        return this.category;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link GuidType }
     *     
     */
    public GuidType getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuidType }
     *     
     */
    public void setGuid(GuidType value) {
        this.guid = value;
    }

    /**
     * Gets the value of the itunesAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesAuthor() {
        return itunesAuthor;
    }

    /**
     * Sets the value of the itunesAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesAuthor(String value) {
        this.itunesAuthor = value;
    }

    /**
     * Gets the value of the itunesSubtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesSubtitle() {
        return itunesSubtitle;
    }

    /**
     * Sets the value of the itunesSubtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesSubtitle(String value) {
        this.itunesSubtitle = value;
    }

    /**
     * Gets the value of the itunesSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesSummary() {
        return itunesSummary;
    }

    /**
     * Sets the value of the itunesSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesSummary(String value) {
        this.itunesSummary = value;
    }

    /**
     * Gets the value of the itunesExplicit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItunesExplicit() {
        return itunesExplicit;
    }

    /**
     * Sets the value of the itunesExplicit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItunesExplicit(String value) {
        this.itunesExplicit = value;
    }

    /**
     * Gets the value of the itunesDuration property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItunesDuration() {
        return itunesDuration;
    }

    /**
     * Sets the value of the itunesDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItunesDuration(XMLGregorianCalendar value) {
        this.itunesDuration = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the enclosure property.
     * 
     * @return
     *     possible object is
     *     {@link EnclosureType }
     *     
     */
    public EnclosureType getEnclosure() {
        return enclosure;
    }

    /**
     * Sets the value of the enclosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnclosureType }
     *     
     */
    public void setEnclosure(EnclosureType value) {
        this.enclosure = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link MediaType }
     *     
     */
    public MediaType getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaType }
     *     
     */
    public void setMedia(MediaType value) {
        this.media = value;
    }

}
