//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.27 at 07:08:04 AM EDT 
//


package lordgasmic.podcastremix.jaxb.podcast;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lordgasmic.podcastremix.jaxb.nsfw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *  
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Rss_QNAME = new QName("", "rss");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lordgasmic.podcastremix.jaxb.nsfw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RssType }
     * 
     */
    public RssType createRssType() {
        return new RssType();
    }

    /**
     * Create an instance of {@link ItunesOwnerType }
     * 
     */
    public ItunesOwnerType createItunesOwnerType() {
        return new ItunesOwnerType();
    }

    /**
     * Create an instance of {@link ChannelType }
     * 
     */
    public ChannelType createChannelType() {
        return new ChannelType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link ItunesImageType }
     * 
     */
    public ItunesImageType createItunesImageType() {
        return new ItunesImageType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ItunesCategoryType }
     * 
     */
    public ItunesCategoryType createItunesCategoryType() {
        return new ItunesCategoryType();
    }

    /**
     * Create an instance of {@link GuidType }
     * 
     */
    public GuidType createGuidType() {
        return new GuidType();
    }

    /**
     * Create an instance of {@link MediaType }
     * 
     */
    public MediaType createMediaType() {
        return new MediaType();
    }

    /**
     * Create an instance of {@link AtomLinkType }
     * 
     */
    public AtomLinkType createAtomLinkType() {
        return new AtomLinkType();
    }

    /**
     * Create an instance of {@link EnclosureType }
     * 
     */
    public EnclosureType createEnclosureType() {
        return new EnclosureType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RssType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rss")
    public JAXBElement<RssType> createRss(RssType value) {
        return new JAXBElement<RssType>(_Rss_QNAME, RssType.class, null, value);
    }

}
